spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_cloud?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
    username: root
    password: example
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
